### ISSUE TITLE
Using DT vs. reactable

### ISSUE THREAD

**Issue by elong0527** [Merck/boxly#9]
Why would we choose `DT` instead of `reactable`?

https://github.com/Merck/boxly/blob/main/R/boxly.R#L188

**Comment by nanxstats** [comment]
The description here is brief and I'm not sure if there are any conversations behind the scene, but I can probably say two things about it:

- DT is a much simpler solution.
- The reactable dependency reactR uses a lower version of the JS dependency karma, which has some vulnerabilities that will trigger Dependabot security alerts if you put the output in a GitHub repo (see [example](https://github.com/nanxstats/nanx.me/security/dependabot?q=is%3Aclosed)). This was patched by Dependabot in react-R/reactR #73 but the PR hasn't been merged since March 2022.
